### ISSUE TITLE
About training

### ISSUE THREAD

**Issue by meiluzhu** [wujiyang/MTCNN_TRAIN#1]
Hello, 
Mr, Wu, there is a problem when I run this code with the following procedure:
1) download the dataset(http://mmlab.ie.cuhk.edu.hk/archive/CNN_FacePoint.htm)
2) then run gen_landmark_12.py
3) python prepare_data/gen_Pnet_train_data.py
4) python prepare_data/assemble_pnet_imglist.py 
5) python train_net/train_p_net.py
but  it happens : accuracy: 1.000000, all_loss: nan, cls_loss: 0.000103, bbox_reg_loss: nan, lr: 0.01000 
although I change the learning rate.

**Comment by wujiyang** [comment]
@zmlGitHub  
1. When trianing PNet and RNet, I didn't usu face landmark regression, so 'run gen_landmark_12.py' is not necessory.  
2. Did  you download the wider face dataset for face classification loss and face bounding box regression loss? gen_PNet_train_data.py is base on this dataset, you can set your own dataset path in the python file.

**Comment by meiluzhu** [comment]
Mr,Wu. Thanks for your answers, I got it !
