### ISSUE TITLE
run test_image.py error

### ISSUE THREAD

**Issue by Amalle** [wujiyang/MTCNN_TRAIN#5]
Hi@wujiyang, Thanks for the work. I got the following error when runing test script. Any advices you can give?
`
$ python test_image.py 

could not broadcast input array from shape (18,997,3) into shape (18,0,3)
could not broadcast input array from shape (45,317,3) into shape (45,0,3)
could not broadcast input array from shape (6,934,3) into shape (6,0,3)
could not broadcast input array from shape (112,993,3) into shape (112,0,3)
could not broadcast input array from shape (413,937,3) into shape (413,0,3)
could not broadcast input array from shape (136,219,3) into shape (136,0,3)
could not broadcast input array from shape (32,1021,3) into shape (32,0,3)
could not broadcast input array from shape (89,756,3) into shape (89,0,3)
could not broadcast input array from shape (672,73,3) into shape (0,73,3)
could not broadcast input array from shape (575,901,3) into shape (575,0,3)
could not broadcast input array from shape (383,289,3) into shape (383,0,3)
could not broadcast input array from shape (59,1018,3) into shape (59,0,3)
could not broadcast input array from shape (116,428,3) into shape (116,0,3)
could not broadcast input array from shape (0,394,3) into shape (337,394,3)
could not broadcast input array from shape (580,766,3) into shape (0,0,3)
could not broadcast input array from shape (127,419,3) into shape (0,419,3)
could not broadcast input array from shape (51,820,3) into shape (51,0,3)
could not broadcast input array from shape (0,358,3) into shape (568,358,3)
could not broadcast input array from shape (35,890,3) into shape (35,0,3)
could not broadcast input array from shape (665,634,3) into shape (0,0,3)
could not broadcast input array from shape (75,979,3) into shape (75,0,3)
Traceback (most recent call last):
  File "test_image.py", line 29, in <module>
    bboxs, landmarks = mtcnn_detector.detect_face(img)
  File "/users/XXX/DNN/MTCNN_TRAIN/tools/detect.py", line 530, in detect_face
    boxes_align, landmark_align = self.detect_onet(img, boxes_align)
  File "/users/XXX/DNN/MTCNN_TRAIN/tools/detect.py", line 419, in detect_onet
    tmp = np.zeros((tmph[i], tmpw[i], 3), dtype=np.uint8)
MemoryError`

**Comment by XiaXuehai** [comment]
`ToTensor() `will div 255.0  in the condition of  `ndarray.dtype=np.uint8` in new pytorch version when convert ndarray to tensor. So the image should divide  255 yourself.

**Comment by wujiyang** [comment]
> `ToTensor() `will div 255.0 in the condition of `ndarray.dtype=np.uint8` in new pytorch version when convert ndarray to tensor. So the image should divide 255 yourself.

thanks for your work about pointing out the mistakes，this is my first pytorch projects so it indeed have a lot of bugs,  hhhhh.

**Comment by github-luffy** [comment]
这是ｐｙｔｏｒｃｈ的版本问题吗？

**Comment by github-luffy** [comment]
把ｉｍａｇｅ_tools文件中的image = image.astype(np.float32)注释掉就可以了

**Comment by github-luffy** [comment]
针对最新的ｐｙｔｏｒｃｈ的版本，把ｉｍａｇｅ_tools文件中的image = image.astype(np.float32)注释掉就可以了
