### ISSUE TITLE
关于O层数据生成的小问题

### ISSUE THREAD

**Issue by ghost** [wujiyang/MTCNN_TRAIN#8]
在利用脚本生成数据的时候，负样本出现很多应该为正样本的数据，楼主遇到过相关的问题吗？是我PR层模型有问题还是调整阈值？最后尝试了，效果都不是很好

**Comment by codylcs** [comment]
the data of Onet input is produced by RNET model,did you gen the data use his model?

**Comment by yja1** [comment]
also have positive image when generate train data for Onet 's negative
